shop/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('detail', views.cart_detail, name='cart_detail'),
    path('cart_add/<product_id>', views.cart_add, name='cart_add'),
    path('cart_remove/<product_id>', views.cart_remove, name='cart_remove'),
]

shop/main/urls.py
from django.urls import path
from . import views
from .views import AdminsView

app_name = 'main'

urlpatterns = [
    path('', views.main, name='main'),
    path('about-us', views.about, name='about'),
    path('search', views.search_results, name='search_results'),
    path('admin/', AdminsView.as_view(), name='admins'),
    path('category/<int:id_cat>', views.category, name='category'),
    path('product/<int:id_prod>', views.product, name='product'),
]

shop/myauth/urls.py
from django.contrib.auth.views import LoginView
from .views import AboutMeView, RegisterView, MyLogoutView
from django.urls import path
from . import views

app_name = 'myauth'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='myauth/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', views.profile, name='profile'),
]

shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create', views.order_create, name='order_create'),
    path('my_orders', views.my_orders, name='my_orders'),
    path('my_orders_items/<int:id>', views.my_orders_items, name='my_orders_items'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('myauth/', include('myauth.urls', namespace='myauth')),
    path('', include('main.urls', namespace='main')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/cart/models.py
from django.db import models

# Create your models here.

shop/main/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(null=False, blank=True, verbose_name='Описание товара')
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2, verbose_name='Цена')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name='Фото товара')
    category_id = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product', args=[self.id])

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Category(models.Model):
    category_id = models.IntegerField()
    name = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(default='description', verbose_name='Описание категории')
    image = models.ImageField(upload_to='categories/%Y/%m/%d', blank=True, verbose_name='Фото')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

shop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(100, 1001, 100)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .cart import Cart
from .forms import CartAddProductForm
from main.models import Product
import random


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    products = Product.objects.all()
    popular_product = random.sample(list(products), 6)
    return render(request, 'cart/detail.html', {'cart': cart, 'popular': popular_product})

shop/cart/templates/cart/base.html
<!doctype html>
{% load static %}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static 'cart/css/main.css' %}">
</head>
<body>
<div id="black-bar">
	<div class="fixed-container">
		Псков, Набережная реки Великой, дом 13
		<div id="telephone">круглосуточная служба поддержки +7-444-888-13-13</div>
	</div>
</div>
<div id="header">
	<div class="fixed-container">
		<a href="{% url 'main:main' %}"><img id="logo" src="{% static 'main/img/logo.png' %}" alt="logo"></a>
		<div id="nav">
			<ul>
				<li>
                    <div class="cart">
                        {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            <a href="{% url 'cart:cart_detail' %}">
                            {{ total_items }} г на
                            {{ cart.get_total_price }} ₽
                            </a>
                        {% else %}
                            <a href="{% url 'main:main' %}">
                            {{ cart.get_total_price }} ₽
                            </a>
                        {% endif %}
                        {% endwith %}
                    </div>
                </li>
				<li><a href="{% url 'cart:cart_detail' %}"><i class="bi bi-cart-check-fill"></i> Корзина </a></li>
				<li><a href="{% url 'main:about' %}"><i class="bi bi-info-square-fill"></i> О нас /</a></li>
				<li><a href="{% url 'main:main' %}"><i class="bi bi-house-door-fill"></i> Главная /</a></li>
				<li><a href="{% url 'myauth:register' %}"><i class="bi bi-person-fill-add"></i> Регистрация /</a></li>
				<li>
					<div class="dropdown">
  						<button class="dropbtn"><i class="bi bi-person-square"></i> Личный кабинет / </button>
  							<div class="dropdown-content">
    							<a href="{% url 'myauth:login' %}"><i class="bi bi-box-arrow-in-right"></i> Войти</a>
								<a href="{% url 'myauth:logout' %}"><i class="bi bi-box-arrow-left"></i> Выйти</a>
  							</div><br>
                    </div>
				</li>
                <li>
                    <form action="{% url 'main:search_results' %}" method="get">
                    <input name="q" type="text" placeholder="Поиск...">
                    </form>
                </li>
			</ul>
		</div>
        {% if perms.main.add_product %}
        <div class="admins">
            <a href="{% url 'main:admins' %}">Администраторам</a>
        </div>
        {% endif %}
	</div>
</div>

{% block content %}
{% endblock %}

<div class="fixed-container">
    <div class="popular">
        Популярные товары
    </div>
</div>
<div class="fixed-container mt-5">
    <div class="container">
        <div class="row">
            {% for el in popular %}
            <div class="col-md-2" style="padding: 0 5px 0 5px">
                <div class="category">
                    <div class="image">
                        <a href="/product/{{ el.id }}">
                            <img src="{% if el.image %}
                            {{ el.image.url }}
                            {% else %}
                            {% static 'main/img/not_img.jpg' %}
                            {% endif %}"
                        style="height: 200px"></a>
                    </div>
                    <div class="info">
                        <p>{{ el.name }}<br><small><i>{{ el.price }} ₽ / 100 г</i></small></p>
                    </div>
                    <div class="go" style="width: 154px">
                        <a href="/product/{{ el.id }}" id="go">Перейти</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<a href="#" id="up-button"><b>Наверх</b><i class="bi bi-arrow-up"></i></a>
<div id="footer">
	<div class="fixed-container">
        <div id="footer-left">
            <div><u>Свяжитесь с нами:</u></div>
            <div>Круглосуточная служба поддержки <i class="bi bi-telephone-outbound-fill"></i></div>
                <div>+7-444-888-13-13</div>
            <div>WatsApp: +7-911-747-60-60 <i class="bi bi-whatsapp"></i></div>
            <div>Telegram: t.me/yournut <i class="bi bi-telegram"></i></div>
        </div>
        <div id="footer-center">
            <div><u>Следите за нами в соцсетях:</u></div>
		    <div>Facebook: <i class="bi bi-facebook"></i></div>
		    <div>Instagram: <i class="bi bi-instagram"></i></div>
		    <div>Twitter: <i class="bi bi-twitter"></i></div>
		    <div>Youtube: <i class="bi bi-youtube"></i></div>
        </div>
        <div id="footer-right">
            <div><u>Псков, Набережная реки Великой, дом 13</u></div>
            <div>О нас: <i class="bi bi-info-square-fill"></i></div>
		    <div>Как заказать: <i class="bi bi-bag-check-fill"></i></div>
		    <div>Доставка: <i class="bi bi-car-front-fill"></i></div>
		    <div>На карте: <i class="bi bi-geo-alt-fill"></i></div>
        </div>
	</div>
</div>
</body>
</html>

shop/cart/templates/cart/detail.html
{% extends "cart/base.html" %}
{% load static %}
{% block title %}
    Корзина
{% endblock %}
{% block content %}
<div class="fixed-container mt-5">
    {% if cart|length <= 0 %}
        <h1>Ваша корзинна пуста</h1><br>
        <div class="button_buy_next">
            <a href="{% url 'main:main' %}" >Начать покупки</a>
        </div>
    {% else %}
        <h1>Ваша корзина</h1><br>
        <table class="cart">
            <thead>
                <tr>
                    <th>Фото</th>
                    <th>Название</th>
                    <th>Количество</th>
                    <th><i class="bi bi-x-octagon-fill"></i></th>
                    <th>Цена</th>
                    <th>Общая стоимость</th>
                </tr>
            </thead>
            <tbody>
            {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}
                                {{ product.image.url }}
                                {% else %}
                                {% static 'main/img/not_img.jpg' %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }} г</td>
                    <td>
                        <div class="del_product">
                            <a href="{% url 'cart:cart_remove' product.id %}">Удалить</a>
                        </div>
                    </td>
                    <td class="num">{{ item.price }} ₽</td>
                    <td class="num">{{ item.total_price }} ₽</td>
                </tr>
            {% endwith %}
            {% endfor %}
            </tbody>
            <tfoot>
                <tr class="total">
                    <th colspan="2">Общая стоимость товаров в корзине:</th>
                    <th colspan="3"></th>
                    <th class="num">{{ cart.get_total_price }} ₽</th>
                </tr>
            </tfoot>
            </table>
            <div class="button_cart">
                <a href="{% url 'main:main' %}" class="button_buy">Продолжить покупки</a>
                <a href="{% url 'orders:order_create' %}" class="button_order">Оформить заказ</a>
            </div>
    {% endif %}
</div>
{% endblock %}