shop/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('detail', views.cart_detail, name='cart_detail'),
    path('cart_add/<product_id>', views.cart_add, name='cart_add'),
    path('cart_remove/<product_id>', views.cart_remove, name='cart_remove'),
]

shop/main/urls.py
from django.urls import path
from . import views
from .views import AdminsView

app_name = 'main'

urlpatterns = [
    path('', views.main, name='main'),
    path('about-us', views.about, name='about'),
    path('search', views.search_results, name='search_results'),
    path('admin/', AdminsView.as_view(), name='admins'),
    path('category/<int:id_cat>', views.category, name='category'),
    path('product/<int:id_prod>', views.product, name='product'),
]

shop/myauth/urls.py
from django.contrib.auth.views import LoginView
from .views import AboutMeView, RegisterView, MyLogoutView
from django.urls import path
from . import views

app_name = 'myauth'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='myauth/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', views.profile, name='profile'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('myauth/', include('myauth.urls', namespace='myauth')),
    path('', include('main.urls', namespace='main')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/main/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(null=False, blank=True, verbose_name='Описание товара')
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2, verbose_name='Цена')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name='Фото товара')
    category_id = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product', args=[self.id])

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Category(models.Model):
    category_id = models.IntegerField()
    name = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(default='description', verbose_name='Описание категории')
    image = models.ImageField(upload_to='categories/%Y/%m/%d', blank=True, verbose_name='Фото')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

shop/main/views.py
import random
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import Category, Product
from cart.forms import CartAddProductForm


def main(request):
    data = Category.objects.all()
    products = Product.objects.all()
    popular_product = random.sample(list(products), 6)
    return render(request, 'main/main.html', {'categories': data, 'popular': popular_product})


def about(request):
    products = Product.objects.all()
    popular_product = random.sample(list(products), 6)
    return render(request, 'main/about.html', {'popular': popular_product})


def category(request, id_cat):
    products = Product.objects.all()
    data = products.filter(category_id=id_cat)
    popular_product = random.sample(list(products), 6)
    cat_name = Category.objects.get(category_id=id_cat)
    return render(request, 'main/category.html',
                  {'data': data, 'name': cat_name.name, 'description': cat_name.description,
                   'popular': popular_product})


def product(request, id_prod):
    products = Product.objects.all()
    data = products.get(id=id_prod)
    popular_product = random.sample(list(products), 6)
    cart_product_form = CartAddProductForm()
    return render(request, 'main/product.html', {'product': data, 'popular': popular_product,
                                                 'cart_product_form': cart_product_form})


def search_results(request):
    query = request.GET.get('q')
    object_list = Product.objects.filter(name__icontains=query)
    products = Product.objects.all()
    popular_product = random.sample(list(products), 6)
    return render(request, 'main/search_results.html', {'object_list': object_list, 'popular': popular_product})


class AdminsView(TemplateView):
    template_name = "admin.html"

shop/main/templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
    Информация о нас
{% endblock %}

{% block content %}
<div class="fixed-container mt-5">
    <h1 class="heading">О нашей компании</h1>
    <br>
    <div class="belka" style="margin-bottom: 30px">
        <a href="{% url 'main:main' %}"><img src="{% static 'main/img/belka.jpg' %}" alt="photo"></a>
    </div>
    <h5>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
    magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</h5>
    <br>
    <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
    magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
    <br>
    <div class="address" style="margin-bottom: 30px">
        <a href="https://yandex.ru/maps/25/pskov/house/naberezhnaya_reki_velikoy_16/ZkEYdQRiTUIPQFttfXRwcH5iYQ==/?ll=
                28.330750%2C57.809777&tilt=0.8726646259971648&z=16.64" target="_blank">
                <img src="{% static 'main/img/address.png' %}" alt="address">
        </a>
    </div>
    <small>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
    magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</small>
</div><br><br>
{% endblock %}

shop/main/templates/main/base.html
<!doctype html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/main.css' %}">
</head>
<body>
<div id="black-bar">
	<div class="fixed-container">
		Псков, Набережная реки Великой, дом 13
		<div id="telephone">Круглосуточная служба поддержки +7-444-888-13-13</div>
	</div>
</div>
<div id="header">
	<div class="fixed-container">
		<a href="{% url 'main:main' %}"><img id="logo" src="{% static 'main/img/logo.png' %}" alt="logo"></a>
		<div id="nav">
			<ul>
				<li>
                    <div class="cart">
                        {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            <a href="{% url 'cart:cart_detail' %}">
                            {{ total_items }} г на
                            {{ cart.get_total_price }} ₽
                            </a>
                        {% else %}
                            <a href="{% url 'main:main' %}">
                            {{ cart.get_total_price }} ₽
                            </a>
                        {% endif %}
                        {% endwith %}
                    </div>
                </li>
				<li><a href="{% url 'cart:cart_detail' %}"><i class="bi bi-cart-check-fill"></i> Корзина </a></li>
				<li><a href="{% url 'main:about' %}"><i class="bi bi-info-square-fill"></i> О нас /</a></li>
				<li><a href="{% url 'main:main' %}"><i class="bi bi-house-door-fill"></i> Главная /</a></li>
				<li><a href="{% url 'myauth:register' %}"><i class="bi bi-person-fill-add"></i> Регистрация /</a></li>
                <li>
                    <div class="dropdown">
  				    	<button class="dropbtn"><i class="bi bi-person-square"></i> Личный кабинет / </button>
  							<div class="dropdown-content">
    							<a href="{% url 'myauth:login' %}"><i class="bi bi-box-arrow-in-right"></i> Войти</a>
								<a href="{% url 'myauth:logout' %}"><i class="bi bi-box-arrow-left"></i> Выйти</a>
  							</div>
					</div><br>
				</li>
                <li>
                    <form action="{% url 'main:search_results' %}" method="get">
                    <input name="q" type="text" placeholder="Поиск...">
                    </form>
                </li>
			</ul>
		</div>
        {% if perms.main.add_product %}
        <div class="admins">
            <a href="{% url 'main:admins' %}">Администраторам</a>
        </div>
        {% endif %}
	</div>
</div>

{% block content %}
{% endblock %}

<div class="fixed-container">
    <div class="popular">
        Популярные товары
    </div>
</div>
<div class="fixed-container mt-5">
    <div class="container">
        <div class="row">
            {% for el in popular %}
            <div class="col-md-2" style="padding: 0 5px 0 5px">
                <div class="category">
                    <div class="image">
                        <a href="/product/{{ el.id }}">
                            <img src="{% if el.image %}
                            {{ el.image.url }}
                            {% else %}
                            {% static 'main/img/not_img.jpg' %}
                            {% endif %}"
                        style="height: 200px"></a>
                    </div>
                    <div class="info">
                        <p>{{ el.name }}<br><small><i>{{ el.price }} ₽ / 100 г</i></small></p>
                    </div>
                    <div class="go" style="width: 154px">
                        <a href="/product/{{ el.id }}" id="go">Перейти</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<a href="#" id="up-button"><b>Наверх</b><i class="bi bi-arrow-up"></i></a>
<div id="footer">
	<div class="fixed-container">
        <div id="footer-left">
            <div><u>Свяжитесь с нами:</u></div>
            <div>Круглосуточная служба поддержки <i class="bi bi-telephone-outbound-fill"></i></div>
                <div>+7-444-888-13-13</div>
            <div>WatsApp: +7-911-747-60-60 <i class="bi bi-whatsapp"></i></div>
            <div>Telegram: t.me/yournut <i class="bi bi-telegram"></i></div>
        </div>
        <div id="footer-center">
            <div><u>Следите за нами в соцсетях:</u></div>
		    <div>Facebook: <i class="bi bi-facebook"></i></div>
		    <div>Instagram: <i class="bi bi-instagram"></i></div>
		    <div>Twitter: <i class="bi bi-twitter"></i></div>
		    <div>Youtube: <i class="bi bi-youtube"></i></div>
        </div>
        <div id="footer-right">
            <div><u>Псков, Набережная реки Великой, дом 13</u></div>
            <div>О нас: <i class="bi bi-info-square-fill"></i></div>
		    <div>Как заказать: <i class="bi bi-bag-check-fill"></i></div>
		    <div>Доставка: <i class="bi bi-car-front-fill"></i></div>
		    <div>На карте: <i class="bi bi-geo-alt-fill"></i></div>
        </div>
	</div>
</div>
</body>
</html>

shop/main/templates/main/category.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
    Категории
{% endblock %}

{% block content %}
<div class="fixed-container">
    <div class="heading">{{ name }}</div>
    <br>
    <div class="description">{{ description }}</div>
</div>
<div class="fixed-container mt-5">
    <div class="container">
        <div class="row">
            {% for el in data %}
            <div class="col-md-4">
                <div class="category">
                    <div class="image">
                        <a href="/product/{{ el.id }}"><img src="{% if el.image %}
                        {{ el.image.url }}
                        {% else %}
                        {% static 'main/img/not_img.jpg' %}
                        {% endif %}"></a>
                    </div>
                    <div class="info">
                        <h4>{{ el.name }}<br></h4><i>{{ el.price }} ₽ / 100 г</i>
                    </div>
                    <div class="go">
                        <a href="/product/{{ el.id }}" id="go">Перейти</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

shop/main/templates/main/main.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
    Главная страница
{% endblock %}

{% block content %}
<div class="fixed-container">
    <div class="heading">
        Твой Орех
    </div>
    <div class="slogan">
        полезные и натуральные продукты по низким ценам
    </div>
</div>
<div class="fixed-container mt-4">
    <div class="container">
        <div class="row">
            {% for c in categories %}
            <div class="col-md-4">
                <div class="category">
                    <div class="image">
                        <a href="/category/{{ c.id }}"><img src="{% if c.image %}
                       {{ c.image.url }}
                       {% else %}
                       {% static 'main/img/not_img.jpg' %}
                       {% endif %}"></a>
                    </div>
                    <div class="info">
                        <h3>{{ c.name }}</h3>
                    </div>
                    <div class="go">
                        <a href="category/{{ c.id }}" id="go">Перейти</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="fixed-container">
    <div class="description">
        <b>Наш магазин</b> - это находка для каждого любителя вкусных и полезных продуктов. Нам удалось собрать в одном
        месте все, что может Вас заинтересовать. Откажитесь от длительных поездок по магазинам своего города,
        ведь теперь, можно сделать заказ продукции в пару кликов.
    </div><br>
</div>
{% endblock %}

shop/main/templates/main/product.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
    Продукты
{% endblock %}

{% block content %}
<div class="fixed-container">
    <div class="card" style="border: 0px; margin-top: 75px">
        <div class="row g-0">
            <div class="col-md-6" style="background-color: #DCDCDC">
                <div class="image_product">
                       <img src="{% if product.image %}
                       {{ product.image.url }}
                       {% else %}
                       {% static 'main/img/not_img.jpg' %}
                       {% endif %}">
                </div>
            </div>
            <div class="col-md-6" style="background-color: #DCDCDC">
                <div class="card-body" style="float: right">
                    <h1><b>{{ product.name }}</b></h1>
                    <ul class="rating" style="padding-left: 0">
                        <li><i class="bi bi-star-fill"></i></li>
                        <li><i class="bi bi-star-fill"></i></li>
                        <li><i class="bi bi-star-fill"></i></li>
                        <li><i class="bi bi-star-fill"></i></li>
                        <li><i class="bi bi-star-half"></i></li>
                    </ul>
                    <h4 ><i>{{ product.price }}</i> ₽ за 100 г</h4><br>
                    <div style="margin-bottom: 15px">
                        <a href="#" id="reviews">Отзывы покупателей о товаре</a>
                    </div>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {{ cart_product_form }}
                        {% csrf_token %}
                        <button type="submit" class="basket"><i class="bi bi-cart-plus-fill"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="description_product_card">
        <b>{{ product.name }}</b> <i>{{ product.description }}</i>
    </div>
</div><br>
{% endblock %}

shop/main/templates/main/search_results.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
  Результаты поиска
{% endblock %}

{% block content %}
<div class="fixed-container">
  <div class="heading">
    Результаты поиска
  </div><br>
  <div class="container">
        <div class="row">
            {% if object_list|length > 0 %}
            {% for product in object_list %}
            <div class="col-md-4">
                <div class="category">
                    <div class="image">
                        <a href="/product/{{ product.id }}"><img src="{% if product.image %}
                       {{ product.image.url }}
                       {% else %}
                       {% static 'main/img/not_img.jpg' %}
                       {% endif %}"></a>
                    </div>
                    <div class="info">
                        <h3>{{ product.name }}<br><small><i>{{ product.price }} <small>₽ / 100 г</small></i></small></h3>
                    </div>
                    <div class="go">
                        <a href="/product/{{ product.id }}" id="go">Перейти</a>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="no_search">
                По Вашему запросу ничего не найдено...
            </div>
            {% endif %}
        </div>
    </div>
</div><br><br>
{% endblock %}