shop/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('detail', views.cart_detail, name='cart_detail'),
    path('cart_add/<product_id>', views.cart_add, name='cart_add'),
    path('cart_remove/<product_id>', views.cart_remove, name='cart_remove'),
]

shop/main/urls.py
from django.urls import path
from . import views
from .views import AdminsView

app_name = 'main'

urlpatterns = [
    path('', views.main, name='main'),
    path('about-us', views.about, name='about'),
    path('search', views.search_results, name='search_results'),
    path('admin/', AdminsView.as_view(), name='admins'),
    path('category/<int:id_cat>', views.category, name='category'),
    path('product/<int:id_prod>', views.product, name='product'),
]

shop/myauth/urls.py
from django.contrib.auth.views import LoginView
from .views import AboutMeView, RegisterView, MyLogoutView
from django.urls import path
from . import views

app_name = 'myauth'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='myauth/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', views.profile, name='profile'),
]

shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create', views.order_create, name='order_create'),
    path('my_orders', views.my_orders, name='my_orders'),
    path('my_orders_items/<int:id>', views.my_orders_items, name='my_orders_items'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('myauth/', include('myauth.urls', namespace='myauth')),
    path('', include('main.urls', namespace='main')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/orders/models.py
from decimal import Decimal
from django.contrib.auth.models import User
from django.db import models
from main.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    email = models.EmailField()
    mobile = models.CharField(max_length=12, verbose_name='Телефон')
    city = models.CharField(max_length=50, verbose_name='Город')
    address = models.CharField(max_length=250, verbose_name='Адрес')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    accept = models.BooleanField(default=False, verbose_name='Статус')

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Заказ {}'.format(self.id)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE, verbose_name='Название')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')
    total_price_product = models.DecimalField(max_digits=10,
                                              decimal_places=2,
                                              default=0,
                                              verbose_name='Общая стоимость продукта'
                                              )

    def __str__(self):
        return '{}'.format(self.order)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Детали заказа'

shop/orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'mobile', 'city', 'address', 'email']

shop/orders/views.py
import random
from django.shortcuts import render
from .models import OrderItem, Order
from .forms import OrderCreateForm
from cart.cart import Cart

from main.models import Product


def order_create(request):
    products = Product.objects.all()
    popular_product = random.sample(list(products), 6)
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'],
                                         total_price_product=item['price'] * item['quantity'] / 100,
                                         )
            cart.clear()

            return render(request, 'orders/created.html',
                          {'order': order, 'popular': popular_product})
    else:
        form = OrderCreateForm
    return render(request, 'orders/create.html',
                  {'cart': cart, 'form': form, 'popular': popular_product})


def my_orders(request):
    orders = Order.objects.filter(user=request.user).order_by('-id')
    products = Product.objects.all()
    popular_product = random.sample(list(products), 6)
    return render(request, 'orders/my_orders.html', {'orders': orders, 'popular': popular_product})


def my_orders_items(request, id):
    products = Product.objects.all()
    popular_product = random.sample(list(products), 6)
    order = Order.objects.get(pk=id)
    order_items = OrderItem.objects.filter(order=order)
    return render(request, 'orders/my_orders_items.html', {'order_items': order_items,
                                                           'order': order,
                                                           'popular': popular_product
                                                           })

shop/orders/templates/orders/create.html
{% extends 'main/base.html' %}
{% block title %}
    Заказ
{% endblock %}

{% block content %}
<div class="fixed-container mt-5">
    {% if not user.is_authenticated %}
    <div class="orders_no">
        Заказы могут делать только авторизованные пользователи<br><br>
        <a class="link-change-profile" href="{% url 'myauth:login' %}">Вход</a>
        <a class="link-order" href="{% url 'myauth:register' %}">Регистрация</a>
    </div>
    {% else %}
    <div class="one">
        <div id="order-info">
            <ul>
                <h5>Ваш заказ:</h5>
                {% for item in cart %}
                <li>
                    <b>{{ item.product.name }}</b>: {{ item.quantity }} г / {{ item.total_price }} ₽
                </li>
                {% endfor %}
            </ul>
            <p><b>Итого: {{ cart.get_total_price }} ₽</b></p>
        </div>
        <form action="" method="post" class="order-form">
        <h2 style="color:#8B4513">Заполните данные для заказа:</h2>
        {{ form.as_p }}
        <p><input style="color: white; height: 50px; font-size:20px; background-color: #8B4513" type="submit" value="Заказать"></p>
        {% csrf_token %}
        </form>
    </div>
    {% endif %}
</div>
{% endblock %}

shop/orders/templates/orders/created.html
{% extends "main/base.html" %}
{% block title %}
    Спасибо
{% endblock %}

{% block content %}
<div class="fixed-container">
    <div class="success">
        <h1>Спасибо за заказ!!!</h1>
        <h4>Заказ принят! Номер Вашего заказа:
        <strong>{{ order.id }}</strong>.</h4>
        <h5>Будем рады видеть Вас снова!!!</h5><br>
        <div class="buy_now">
           <a href="{% url 'main:main' %}" >Начать покупки</a>
        </div>
    </div>
</div>
{% endblock %}

shop/orders/templates/orders/my_orders.html
{% extends 'main/base.html' %}
{% block title %}
    История заказов
{% endblock %}

{% block content %}
<div class="fixed-container">
    {% if not orders %}
    <div class="orders_no">
        Заказов еще не было.....
    </div><br>
        <div class="buy_now">
           <a href="{% url 'main:main' %}" >Начать покупки</a>
        </div>
    {% else %}
    <div class="heading">
        История заказов
    </div><br>
    <div class="order_info">
        <h3>Ваши заказы:</h3>
        <ul>
            {% for order in orders %}
            <li>
                <p>
                    <b>Номер заказа:</b> {{ order.id }} /
                    <b>Создан:</b> {{ order.created }}
                </p>
            </li>
            <a class="link_order_detail" href="{% url 'orders:my_orders_items' order.id %}">Детали заказа</a>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
</div>
{% endblock %}

shop/orders/templates/orders/my_orders_items.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
    Детали заказа
{% endblock %}

{% block content %}
<div class="fixed-container">
   {% if order_items|length <= 0 %}
    <div class="orders_no">
        Пустой заказ...
    </div><br>
    <div class="buy_now">
        <a href="{% url 'main:main' %}" >Начать покупки</a>
    </div>
    {% else %}
    <div class="heading">
        Детали заказа № {{order.id}}
    </div><br>
        <table class="detail_order">
        <thead>
        <tr>
            <th>Фото</th>
            <th>Название</th>
            <th>Количество</th>
            <th>Цена</th>
            <th>Общая стоимость</th>
        </tr>
        </thead>
        <tbody>
        {% for item in order_items %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}"><img src="{% if item.product.image %}
                       {{ item.product.image.url }}
                       {% else %}
                       {% static 'main/img/not_img.jpg' %}
                       {% endif %}"></a>
                    </td>
                    <td>{{ item.product.name }}</td>
                    <td>{{ item.quantity }} г</td>
                    <td class="num">{{ item.price }} ₽</td>
                    <td class="num">{{ item.total_price_product }} ₽ </td>
                </tr>
            {% endwith %}
        {% endfor %}
        </tbody>
        </table>
    {% endif %}
</div>
{% endblock %}