shop/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('detail', views.cart_detail, name='cart_detail'),
    path('cart_add/<product_id>', views.cart_add, name='cart_add'),
    path('cart_remove/<product_id>', views.cart_remove, name='cart_remove'),
]

shop/main/urls.py
from django.urls import path
from . import views
from .views import AdminsView

app_name = 'main'

urlpatterns = [
    path('', views.main, name='main'),
    path('about-us', views.about, name='about'),
    path('search', views.search_results, name='search_results'),
    path('admin/', AdminsView.as_view(), name='admins'),
    path('category/<int:id_cat>', views.category, name='category'),
    path('product/<int:id_prod>', views.product, name='product'),
]

shop/myauth/urls.py
from django.contrib.auth.views import LoginView
from .views import AboutMeView, RegisterView, MyLogoutView
from django.urls import path
from . import views

app_name = 'myauth'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='myauth/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', views.profile, name='profile'),
]

shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create', views.order_create, name='order_create'),
    path('my_orders', views.my_orders, name='my_orders'),
    path('my_orders_items/<int:id>', views.my_orders_items, name='my_orders_items'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('myauth/', include('myauth.urls', namespace='myauth')),
    path('', include('main.urls', namespace='main')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/main/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(null=False, blank=True, verbose_name='Описание товара')
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2, verbose_name='Цена')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name='Фото товара')
    category_id = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product', args=[self.id])

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Category(models.Model):
    category_id = models.IntegerField()
    name = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(default='description', verbose_name='Описание категории')
    image = models.ImageField(upload_to='categories/%Y/%m/%d', blank=True, verbose_name='Фото')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

shop/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    mobile = models.CharField(max_length=12, verbose_name='Телефон', null=True, blank=False)
    city = models.CharField(max_length=50, verbose_name='Город', null=True, blank=False)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан', null=True, blank=True)

    class Meta:
        verbose_name = 'Профиль пользователя'
        verbose_name_plural = 'Профили пользователей'

    def __str__(self):
        return str(self.user)

shop/myauth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import *


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': 'form-input'}))
    last_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')


class ProfileUpdateForm(forms.ModelForm):
    mobile = forms.CharField(label='Телефон', widget=forms.TextInput(attrs={'class': 'form-input'}))
    class Meta:
        model = Profile
        fields = ('mobile', 'city')

shop/myauth/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView
from .forms import RegisterUserForm, LoginUserForm, UserUpdateForm, ProfileUpdateForm
from .models import Profile


class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"


class LoginView(CreateView):
    form_class = LoginUserForm
    template_name = "myauth/login.html"
    success_url = reverse_lazy("myauth:about-me")


class RegisterView(CreateView):
    form_class = RegisterUserForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(self.request, username=username, password=password)
        login(request=self.request, user=user)
        return response


class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('myauth:about-me')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'myauth/profile.html', context)

shop/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}
{% block title %}
  Личный кабинет
{% endblock %}

{% block content %}
<div class="fixed-container">
  <div class="heading">
    Личный кабинет
  </div>
  <div class="user-info"><br>
  {% if user.is_authenticated %}
    <h5>Информация о <strong>{{ user.username }}</strong></h5>
    <p><b>Логин:</b> {{ user.username }}</p>
    <p><b>Имя:</b> {{ user.first_name }}</p>
    <p><b>Фамилия:</b> {{ user.last_name }}</p>
    <p><b>Email:</b> {{ user.email }}</p>
    <p><b>Телефон:</b> {{ user.profile.mobile }}</p>
    <p><b>Город:</b> {{ user.profile.city }}</p>
    <a class="link-order" href="{% url 'orders:my_orders' %}">История заказов</a>
    <a class="link-change-profile" href="{% url 'myauth:profile' %}">Изменить</a>
  </div>
  {% else %}
      <div class="user-info">
        <h2>Войдите в личный кабинет</h2>
      </div>
  {% endif %}
</div>
</div>

{% endblock %}

shop/myauth/templates/myauth/base.html
<!doctype html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static 'myauth/css/main.css' %}">
</head>
<body>
<div id="black-bar">
	<div class="fixed-container">
		Псков, Набережная реки Великой, дом 13
		<div id="telephone">круглосуточная служба поддержки +7-444-888-13-13</div>
	</div>
</div>
<div id="header">
	<div class="fixed-container">
		<a href="{% url 'main:main' %}"><img id="logo" src="{% static 'main/img/logo.png' %}" alt="logo"></a>
		<div id="nav">
			<ul>
				<li>
					 <div class="cart">
                        {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            <a href="{% url 'cart:cart_detail' %}">
                            {{ total_items }} г на
                            {{ cart.get_total_price }} ₽
                            </a>
                        {% else %}
                            <a href="{% url 'main:main' %}">
                            {{ cart.get_total_price }} ₽
                            </a>
                        {% endif %}
                        {% endwith %}
                    </div>
				</li>
				<li><a href="{% url 'cart:cart_detail' %}"><i class="bi bi-cart-check-fill"></i> Корзина</a></li>
				<li><a href="{% url 'main:about' %}"><i class="bi bi-info-square-fill"></i> О нас /</a></li>
				<li><a href="{% url 'main:main' %}"><i class="bi bi-house-door-fill"></i> Главная /</a></li>
				<li><a href="{% url 'myauth:register' %}"><i class="bi bi-person-fill-add"></i> Регистрация /</a></li>
				<li>
                    <div class="dropdown">
  					    <button class="dropbtn"><i class="bi bi-person-square"></i> Личный кабинет / </button>
                        <div class="dropdown-content">
    						<a href="{% url 'myauth:login' %}"><i class="bi bi-box-arrow-in-right"></i> Войти</a>
							<a href="{% url 'myauth:logout' %}"><i class="bi bi-box-arrow-left"></i> Выйти</a>
  						</div><br>
				    </div>
				</li>
                <li>
                    <form action="{% url 'main:search_results' %}" method="get">
                    <input name="q" type="text" placeholder="Поиск...">
                    </form>
                </li>
			</ul>
		</div>
        {% if perms.main.add_product %}
        <div class="admins">
            <a href="{% url 'main:admins' %}">Администраторам</a>
        </div>
        {% endif %}
	</div>
</div>

{% block content %}
{% endblock %}

<a href="#" id="up-button"><b>Наверх</b><i class="bi bi-arrow-up"></i></a>
<div id="footer">
	<div class="fixed-container">
        <div id="footer-left">
            <div><u>Свяжитесь с нами:</u></div>
            <div>Круглосуточная служба поддержки <i class="bi bi-telephone-outbound-fill"></i></div>
                <div>+7-444-888-13-13</div>
            <div>WatsApp: +7-911-747-60-60 <i class="bi bi-whatsapp"></i></div>
            <div>Telegram: t.me/yournut <i class="bi bi-telegram"></i></div>
        </div>
        <div id="footer-center">
            <div><u>Следите за нами в соцсетях:</u></div>
		    <div>Facebook: <i class="bi bi-facebook"></i></div>
		    <div>Instagram: <i class="bi bi-instagram"></i></div>
		    <div>Twitter: <i class="bi bi-twitter"></i></div>
		    <div>Youtube: <i class="bi bi-youtube"></i></div>
        </div>
        <div id="footer-right">
            <div><u>Псков, Набережная реки Великой, дом 13</u></div>
            <div>О нас: <i class="bi bi-info-square-fill"></i></div>
		    <div>Как заказать: <i class="bi bi-bag-check-fill"></i></div>
		    <div>Доставка: <i class="bi bi-car-front-fill"></i></div>
		    <div>На карте: <i class="bi bi-geo-alt-fill"></i></div>
        </div>
	</div>
</div>
</body>
</html>

shop/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}
{% block title %}
    Вход
{% endblock %}

{% block content %}
<div class="fixed-container">
    <div id="reg-form">
        <h3>Добро пожаловать!</h3>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Войти</button>
        </form>
    </div>
</div>
{% endblock %}

shop/myauth/templates/myauth/profile.html
{% extends 'myauth/base.html' %}
{% block title %}
	Изменение профиля пользователя
{% endblock %}

{% block content %}
<div class="fixed-container">
	<div class="heading">
		Изменение данных профиля
	</div>
  	<div id="reg-form">
        <h3>Ваш профиль</h3>
        <form method=post>
        {% csrf_token %}
        {{ u_form.as_p }}
		{{ p_form.as_p }}
        <button type="submit">Обновить</button>
        </form>
    </div>
</div>
{% endblock%}

shop/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}
{% block title %}
  Регистрация
{% endblock %}

{% block content %}
<div class="fixed-container">
    {% if not request.user.is_authenticated %}
        <div id="reg-form">
            <h3>Добро пожаловать!</h3>
            <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Регистрация</button>
            </form>
        </div>
    {% else %}
        <div class="user-info mt-">
            <br><h4>Сначала нужно выйти из личного кабинета!</h4>
        </div>
        <div class="logout">
            <a href="{% url 'myauth:logout' %}">Выход из личного кабинета</a>
        </div>
    {% endif %}
</div>
{% endblock %}